### ISSUE TITLE
Comparing password is still taking too much time

### ISSUE THREAD

**Issue by sadiqhabib** [meanie/express-seed#2]
Hi I saw your issues which is closed now but problem is still there
[Issue](https://github.com/dcodeIO/bcrypt.js/issues/42)
Do you have any idea to solve this issue becaus eits taking more than 2 seconds to compare single password with 15 rounds.
Thank you

**Comment by adamreisnz** [comment]
Are you using bcrypt.js? If so it's best to switch to native bcrypt package which will speed it up.

If you are already using bcrypt then that's just how long it takes. You could try to increase resources on the server or reduce the number of rounds, or run the script asynchronously.

**Comment by sadiqhabib** [comment]
Thank you for your reply, I am already using native **bcrypt** package with good development machine specs and right now its offline. so I hope it will take less time on server.  Thank you again.
